version: "3.1"

services:
  db:
    image: postgres
    restart: always
    container_name: pg-db
    environment:
      POSTGRES_DB: sqllearn
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./mount:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   container_name: pg-admin
  #   ports:
  #     - 8080:8080
